### ISSUE TITLE
[JSSCP Phulwari] Data Migration

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/JSSCP#1]
Data is in [this google drive file](https://docs.google.com/spreadsheets/d/1SYjRmm9IkaWDzEnCq_znmxanQvQlhUtr/edit#gid=1357041330) with following colour code:

Yellow(column) - Registration data
Blue (column) - Enrolment Data
Purple (column) - Anthropometry Assessment

**Comment by sidsamanvay** [comment]
Waiting for data corrections. until then on hold.
