### ISSUE TITLE
[JSSCP][Report][HTN]Patients enrolled with any complications

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#104]
Req Doc- https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1262509813&range=2:2

- Aggregate and Line list.
- Link the case from line list to DEA.
- This report will be from enrolment data.

**Comment by sachsk** [comment]
-RBS denominator: No. of individuals who have completed 12-month duration from last RBS value-filled in the followup

**Comment by sachsk** [comment]
On hold due to unclear  requirements

**Comment by garimadosar5** [comment]
QA Notes - 
- Exit/non-exit status filter is not there.
