### ISSUE TITLE
Fix the cancellation form visit schedule rule

### ISSUE THREAD

**Issue by hithacker** [avniproject/JSSCP#107]
Bugsnag error https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/5f59e29200bf060017dca1e9

Refer this bug card for further details--
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-client/392

**Comment by nupoorkhandelwal** [comment]
'programEncounter', { voided: false,
10-14 08:27:47.666  3593  4031 I ReactNativeJS:   uuid: 'e9f344af-bcfc-4c55-a31d-71e98f33a305',
10-14 08:27:47.666  3593  4031 I ReactNativeJS:   observations: [],
10-14 08:27:47.666  3593  4031 I ReactNativeJS:   cancelObservations: [],
10-14 08:27:47.666  3593  4031 I ReactNativeJS:   encounterDateTime: Wed Oct 14 2020 08:27:47 GMT-0400 (EDT),
10-14 08:27:47.666  3593  4031 I ReactNativeJS:   encounterType: 
10-14 08:27:47.666  3593  4031 I ReactNativeJS:    { uuid: 'bb2ea3b7-55c8-4bab-8ee5-b71eec633408',
10-14 08:27:47.666  3593  4031 I ReactNativeJS:      name: 'Child PNC',
10-14 08:27:47.666  3593  4031 I ReactNativeJS:      operationalEncounterTypeName: 'Child PNC',
10-14 08:27:47.666  3593  4031 I ReactNativeJS:      displayName: 'Child PNC',
10-14 08:27:47.666  3593  4031 I ReactNativeJS:      voided: false,
10-14 08:27:47.666  3593  4031 I ReactNativeJS:      encounterEligibilityCheckRule: '',
10-14 08:27:47.666  3593  4031 I ReactNativeJS:      active: true },
10-14 08:27:47.666  3593  4031 I ReactNativeJS:   programEnrolment: undefined }
10-14 08:27:47.666  3593  4031 I ReactNativeJS: 'programEncounter.programEnrolment', undefined
