### ISSUE TITLE
[JSSCP] Move verbal autopsy & death forms from UAT to Live org

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#108]
Tasks--

Move verbal autopsy and death encounter forms and its respective concepts, form mappings from UAT to Live org.

1. Download bundle from JSSCP UAT
2. Keep only new encounters -Verbal autopsy and death.
3. Concepts
4. All the four forms
5. Its respective form mappings
6. Upload  them
7.Test the forms under general tab> new form.

**Comment by garimadosar5** [comment]
QA Notes- 
@nupoorkhandelwal 
Please check user group. Death and verbal autopsy are not enabled for MCH users.
