### ISSUE TITLE
[JSSCP][Phulwari support] Monthly tracking report is not showing one of the cluster

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#109]
ticket - https://avni.freshdesk.com/a/tickets/700

report - https://reporting.avniproject.org/question/1266

**Comment by nupoorkhandelwal** [comment]
Fix - Achanakmar Cluster Catchment has Achanakmar cluster as the location while other catchments have villages of the respective clusters.

**Comment by garimadosar5** [comment]
@nupoorkhandelwal Please go ahead with the steps. User has synced the data.
