### ISSUE TITLE
[JSSCP][Support] Few visits should not be scheduled for "other" village

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#115]
Ticket - https://avni.freshdesk.com/a/tickets/852

If _Other_ Village s selected in the registration form then
- **following visits should be there for non-programme village pregnant women**
1. ANC clinic visit
2. Lab visit
3. Referral status 1
4. Referral status 2

- **The following visit is not required**
ANC home visit
PNC visits for both mother and child

**Comment by sachsk** [comment]
Made changes in
- Delivery form visit scheduling
- Child birth form
- ANC visit cancel
