### ISSUE TITLE
[JSSCP][Support] Issues with PNC visit schedule

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#116]
ticket- https://avni.freshdesk.com/a/tickets/851

Link to PNC scheduling - 
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=2119102511

PNC visit is not getting scheduled properly. (refer ticket). Sometimes PNC 4 get scheduled before PNC 3.

**Comment by sachsk** [comment]
On hold:
need to do more testing on the developer side.

**Comment by garimadosar5** [comment]
not fixed-
- On edit it schedule a new/next PNC visit. This way we can have more that one PNC in planned visit. (need to discuss this further)

**Comment by sachsk** [comment]
On hold due to sync taking too much time.

**Comment by garimadosar5** [comment]
QA Notes - 
- Child and Mother PNC is not in sync.
Child Case - Sundar Lal
Mother case - Rani Gond (Name is in hindi in app).

For the child and mother delivery date is same but PNC are getting scheduled differently.
