### ISSUE TITLE
[JSSCP] TB General encounters visit scheduling

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#143]
https://docs.google.com/spreadsheets/d/1FB29IqJ-afqWk7OnYSAfTiMXUTYlp8vXwcg6gImW-gk/edit#gid=2119102511&range=6:6

- [x] Family Screening

- [ ] Family members screening

- [x] Mantoux Test Result

- [x] INH Prophylaxis follow up

- [x] On Cancel INH Prophylaxis follow up visit

**Comment by garimadosar5** [comment]
QA Notes - 
Family member screening form is getting scheduled for TB patient. (already enrolled in TB program). case - Test Enrol
![Screen Shot 2021-01-14 at 6.36.26 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0aa679d9-ff3d-41d3-97f0-98c5df9a53e0)

**Comment by sachsk** [comment]
On hold
right now we are not able to get all members of the household from the household Member.
for that, we have to inject members into groups.

**Comment by garimadosar5** [comment]
QA Notes - 
- In scheduling, it is showing family screening form but in Household, there is no form schedule.
- Case - TB schedule screening
- There is NULL with Household name. (it is the same issue as RWB)
![Screenshot_2021-01-27-12-32-15-99_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/1d830c70-536b-4d24-8504-7676147d9097)
