### ISSUE TITLE
[JSSCP][Report][TB] Patients diagnosed with different types of TB

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#147]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1489099110&range=2:2

- Aggregate report
- Check all the filters
- Link to line list
- Link line lists with the DEA.

Some work on this report has been done by Vinod. Check the existing report.

**Comment by vindeolal** [comment]
There are some doubts around filters, so not implementing filters right now.

**Comment by vindeolal** [comment]
Moving it on hold. Can implement filters once the requirement is clear.
