### ISSUE TITLE
[JSSCP] TB lab test scheduling

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#149]
https://docs.google.com/spreadsheets/d/1FB29IqJ-afqWk7OnYSAfTiMXUTYlp8vXwcg6gImW-gk/edit#gid=2119102511&range=4:4

Separate forms for each of the following--

- [x] **Test result - CBNAAT**, if CBNAAT is selected in followup

- [x] **Test result - LPA**, , if LPA is selected in followup

- [x] **Test result - LJ**, , if LJ is selected in followup

- [x] **Test results from clinic** If any of these is selected in followup Sputum AFB, HB, RBS, PP2BS, FBS

- [x] **Test results from Ganiyari Lab** , In any other test is select in followup apart from the above mentioned ones.

Add skip logic for test result fields based on the above encounter names.

**Comment by sachsk** [comment]
On hold 
requirements are not clear.
