### ISSUE TITLE
[JSSCP] Change in Medicine group for all the NCD followup forms

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#153]
- Hypertension Followup 
https://docs.google.com/spreadsheets/d/1nCI079lBmUzNUA4KOB3fdMn7nz7EKVc6sk8RLycL56w/edit#gid=836611880&range=33:33
        -> Change in Row 33 and 34. Add one question "Medicine status"  and logic in row 34. and then add logic of Medicines as mentioned.
- Diabetes Followup
https://docs.google.com/spreadsheets/d/1nCI079lBmUzNUA4KOB3fdMn7nz7EKVc6sk8RLycL56w/edit#gid=934442207&range=43:43
        -> Change in Row 43 and 44. Add one question "Medicine status"  and logic in row 44. and then add logic of Medicines as mentioned.
- Sickle cell Followup
https://docs.google.com/spreadsheets/d/1nCI079lBmUzNUA4KOB3fdMn7nz7EKVc6sk8RLycL56w/edit#gid=1647727136&range=32:33
       -> Change in Row 32 and 33. Add one question "Medicine status"  and logic in row 33. and then add logic of Medicines as mentioned.
- Epilepsy followup
         -> Change in Row 32 and 33. Add one question "Medicine status"  and logic in row 33. and then add logic of Medicines as mentioned.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- The medicines are not showing automatically if there is no change in medicines.

**Comment by sachsk** [comment]
currently, it's not possible to show autoselected answer in (multi-select/single select)questions
