### ISSUE TITLE
[JSSCP][Report][HTN] Patients with any abnormal labs in the last visit

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#155]
Req Doc - https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1262509813&range=18:18

- Aggregate and line listing report.
- Link the cases from line listing to DEA.
- This report will be taken from the latest visit. Enrolment or followup/Lab test result.

**Comment by sachsk** [comment]
On hold, report is removed by Ravi
