### ISSUE TITLE
[JSSCP][Report][HTN] Disease Status

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#157]
Req doc - https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1262509813&range=41:41

- Aggregate and line listing report.
- Link the cases from line listing to DEA.
- This report will be taken from the latest visit. Enrolment or followup/Lab test result.

**Comment by garimadosar5** [comment]
QA Notes - 
- There are 298 cases in-app and in the report, it is showing 305.

**Comment by sachsk** [comment]
@garimadosar5  numbers in app are showing less because some cases are exited.

**Comment by garimadosar5** [comment]
QA Notes 2- 
- Remove exited cases.
