### ISSUE TITLE
[JSSCP][Report][HTN] Patients on amlodipin with disease status

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#158]
Req doc - 
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1262509813&range=45:45

- Aggregate and line listing report.
- Link the cases from line listing to DEA.
- This report will be taken from the latest visit. Enrolment or followup/Lab test result.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  @sachsk  This report should have "Total number of HTN patients" and "Total number of HTN patients on amlodipin" as new rows. 

Please add them. Right now it is not clear from the percentages/numbers that how many HTN patients are there in the system  and who all are on amlodipin!

**Comment by garimadosar5** [comment]
QA Notes - 
- Indicator - "Total patients on amlodipin", is always 100%. what is the this should be (total patients on amlodipin/total hypertension patients)*100. 
Please check.
