### ISSUE TITLE
[JSSCP][Report][Diabetes]Patients on various medicines with disease controlled status

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#164]
Req doc - https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1367201437&range=43:43

- This is an aggregate report.
- Check the filters
- Link the report to line listing'
- Link line listing to DEA.

**Comment by sachsk** [comment]
On hold, report is removed by Ravi
