### ISSUE TITLE
[JSSCP][Report][SC]No of patients enrolled with history

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#166]
Req doc - https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=242362992&range=6:6

- Aggregate report
- Check all the filters
- Link report to line listing
- Link line listing to DEA.

**Comment by sachsk** [comment]
On hold, report is removed by Ravi
