### ISSUE TITLE
[JSSCP][Report][Epilepsy]No of patients enrolled with type of disease		

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#171]
Req doc - https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=455652739&range=2:2

- Aggregate report
- Check all the filter
- Line listing for this report
- Link line listing to DEA.

**Comment by garimadosar5** [comment]
QA Notes - 
- In this report, total % is coming more than 100%. (88.89+11.11+11.11 = 111.11).
- If someone is enrolled twice then it is coming twice in number. (Case - Testy Tasty).

**Comment by sachsk** [comment]
if someone enrolled twice we have to count it twice Confirmed with Ravi.
