### ISSUE TITLE
[JSSCP] HTN Issues - Blocker for go live

### ISSUE THREAD

**Issue by arjunk** [avniproject/JSSCP#180]
- [x] Epilepsy and Diabetes have same colour. that should be changed.
- [x] Spelling Mistake : Baseline ser creatinin, I think it should be Baseline serum creatinine
- [x] HTN Enrolment : when entering medicine it even allows entering 10 times per day. we should either keep this as coded or keep absolute low and high range. 
- [x] HTN Enrolment : The Counselling points be shown first and then the question should be asked "Initial counselling done"? To be done everywhere
- [ ] HTN Follow up : Do we have sample forms filled? I am wondering if the users will be able to fill in text box of new complaints. i think it should be coded answer. 
- [ ] HTN Follow up: The question says No. of days Medicine taken previous month. what if the patient was previously seen in less than 1 months?
- [ ] Translations missing at multiple places. please check the app thoroughly and get the missing translations from Ravi

**Comment by garimadosar5** [comment]
QA Notes - 
- Second point, fix this for all the module. Diabetes and TB also.
