### ISSUE TITLE
[JSSCP][Report]Patient treatment status

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#188]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=1383783120&range=71:71

- [x] This is a common report for all the NCD programs and TB program
- [x] This is an Aggregate report.
- [x] Link this to the common line list
- [x] Check for filters
- [x] Link line list cases to DEA.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- There are a lot of cases in HTN and DM but in report showing 5-6 cases only. check once.

**Comment by sachsk** [comment]
We have changed this question that's why it is not calculated for old followups.
Count is correct.
