### ISSUE TITLE
[JSSCP][Report] Existing report copy from PHNI reports.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#19]
#### Refer only section - `Reports from PHNI`

For "All Children" Report refer the format -  https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=727061029

@sachsk  
Will do kick-off for this before you start.

**Comment by garimadosar5** [comment]
@sachsk 
- Reports are not running on Production.

**Comment by sachsk** [comment]
- 

- Report **All Children** :- in these report Anthropometry Assessment form takes height and it is skippable so because of these there are some cases in which height is skipped for first and last visit. so now I have taken the first and last occurrence of height from encounters

**Comment by sachsk** [comment]
@garimadosar5 
the values taken for height in all forms are from the first and last encounter resp. if there is no data for height in first or last encounter it will show empty
