### ISSUE TITLE
[JSSCP][Report] Phulwari Monthly Tracking.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#20]
##### Ref Doc - https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=643598674

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**Comment by garimadosar5** [comment]
QA Notes - 
- Remove Qa user and Admin users fro the list.
-

**Comment by sachsk** [comment]
@garimadosar5 
QA chages:- Done

**Comment by arjunk** [comment]
One row is to be shown for the data importer users.

**Comment by garimadosar5** [comment]
- In the master catchment, there should be all the villages and Phulwari. why is it showing only 4 villages and 10 Phulwaris?
- And in future if we assign these phulwaris to some cluster. what will happen? Will that phulwari be removed from master catchment number?
