### ISSUE TITLE
[JSSCP][MCH] Support ticket #1107 visit scheduling changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#206]
Changes in the visit scheduling, highlighted in the sheet.Also it is explained in the ticket as well.

https://avni.freshdesk.com/a/tickets/1107

https://docs.google.com/spreadsheets/d/1mfk_3eknQoKtagteQN-x-x9TSGzts1AKWX5no1zgfDg/edit#gid=2119102511

**Comment by garimadosar5** [comment]
QA Notes - 
- Case - Test mother child. (Pregnancy)
Delivery date - 10-Feb-2021
PNC 1 scheduled - 15 Feb 2021
PNC 1 completed - 15 Feb 2021
No visit scheduled as PNC 5.
