### ISSUE TITLE
[JSSCP][Report] Children Moved to lower grade

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#21]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=643598674

**Comment by sachsk** [comment]
https://reporting.openchs.org/question/696?year=2019&month=1

**Comment by garimadosar5** [comment]
QA Notes -

- Definition of lower grade- 1 to 2, 2 to 3 
- Also, include no change children in the list.
