### ISSUE TITLE
[JSSCP][Support] Issue in Phulwari report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#212]
https://avni.freshdesk.com/a/tickets/1222

**Comment by sachsk** [comment]
date filter is on enrolment date

**Comment by garimadosar5** [comment]
QA Notes - 
- For Some cases Phulwari name is missing.
- One case is coming more than once with different Catchment name.
- There should be no catchment as MCH program area for phulwari cases.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Add a filter "Catchment" and do not show JSS master catchment in the list of the catchment.
