### ISSUE TITLE
[JSSCP][Report] Children moved to upper grade

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#22]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=643598674

**Comment by sachsk** [comment]
https://reporting.openchs.org/question/697?year=2019&month=5

**Comment by garimadosar5** [comment]
QA Notes - 
- Upper grade means - moved from 2 to 1, 3 to 2.
