### ISSUE TITLE
[JSSCP][Support] All children report filter values.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#235]
https://avni.freshdesk.com/a/tickets/1467

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Some phulwaris are there in the report but not there in the filter and also, I cannot find them in the system.
Eg: Parshuram, Phagani, Phoolsingh etc.

**Comment by sachsk** [comment]
fixed the report for some individuals it was showing the household name.

**Comment by garimadosar5** [comment]
QA Notes - 
- There was a Phulwari filter as well, Showing in the SS attached to the ticket. Did you remove that?
