### ISSUE TITLE
[JSSCP][Support] Child Birth report is not showing numbers.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#241]
Report Link - 
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FJSSCP%2FReports%2FAggregate%2FAggregates&reportUnit=%2FJSSCP%2FReports%2FAggregate%2FAggregates%2FChild_Birth&standAlone=true

Ticket - https://avni.freshdesk.com/a/tickets/1559

**Comment by sachsk** [comment]
We are not capturing birth weight in any form so we can't show birth count in the report.
Added birth weight field on child birth form now.
