### ISSUE TITLE
[JSSCP][Support] Report timeout error

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#242]
https://avni.freshdesk.com/a/tickets/1565

**Comment by nupoorkhandelwal** [comment]
new report link -- https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FJSSCP%2FReports%2FAggregate%2FAggregates&reportUnit=%2FJSSCP%2FReports%2FAggregate%2FAggregates%2FHigh_risk_pregnancy&standAlone=true
