### ISSUE TITLE
[JSSCP] [Support] Followup visits are not getting scheduled for TB program

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#246]
https://avni.freshdesk.com/a/tickets/1626

Check all the TB program-related visits.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Follow-up visits is not getting scheduled.
![Screen Shot 2022-02-23 at 6.13.30 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/5b51372b-29c4-45fc-882b-409107e5a022)

**Comment by sachsk** [comment]
This is bug in Webapp created bug card for this https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/719

On mobile app its working fine
