### ISSUE TITLE
[App] Scheduling Verbal Autopsy form for adult in case of Death

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#248]
Verbal Autopsy Adult encounter has been already created by Ravi in Staging - need to move it to production.

Subject Type of Encounter - Individual.
When to schedule - When for any adult individual, the reason for exit is Death mentioned in exit form for any of the programs they are enrolled in.

Do the visit scheduling as of now, can move this to production when we move the changes to production

**Comment by nupoorkhandelwal** [comment]
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/744

Once this bug is fixed, we can pick it up.

**Comment by utkarshavni** [comment]
Moving this to Ready as the bug is fixed.

**Comment by utkarshavni** [comment]
Can schedule this visit when user does a general death encounter or program exit citing death as reason. This will not be applicable for those above 18 years of age.

**Comment by Gojo-Taqi** [comment]
Created a bug card, link below
https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/756

**Comment by pkundu** [comment]
@AnjaliBhagabati to check with Noopur
