### ISSUE TITLE
[Report: JSSCP] Adding indicators for death rate in Birth and death rate for MCH reports

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#250]
Report reference sheet: (Row ids: 141 to 144)
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=96095858

Formula to calculate each indicator has been given in the referred sheet.
1.  Infant Mortality Rate - 
2. Under 5 Proportional mortality rate
3. <50 Years Proportional mortality rate
4. >50 Years Proportional mortality rate

Data Source is Exit form.

Report link :https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FJSSCP%2FReports%2FAggregate%2FAggregates&reportUnit=%2FJSSCP%2FReports%2FAggregate%2FAggregates%2FBirth_and_Death_Rates&standAlone=true

**Comment by sachsk** [comment]
We have to add only two indicators to the report as the rest two are irrelevant in this report.
Also, this thing is discussed with the client (Ravi).
