### ISSUE TITLE
[JSSCP] Offline Dashboard for MCH Worker

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#252]
**Motivation:**
MCH worker require the details of beneficiaries as mentioned below in details for better monitoring and reporting of their work.

**Goal:**
MCH worker should see a custom offline dashboard with following indicators on the home page of Avni.
https://docs.google.com/spreadsheets/d/1cLXk9dUHfvyqak1sODnmjKW9xLk87uc3YGTCbkUmpO4/edit#gid=0
1. No of pregnant women - (enrolled and not delivered)
2. No of deliveries (For the specific month)
3. No of births (For the specific month)
4. No of children for post natal visits
5. No of mothers for post partum visits
6. No of child deaths (all)
7. No of maternal deaths
8. Due Visits- Filter (Pregnant, PPMC, HBNC, Lab)
9. No of cancelled visits
10. Completed visits- User wise

**Comment by utkarshavni** [comment]
- [ ] No. of child deaths count does not get updated.
- [ ] Maternal death count is not updated.
- [ ] PNC visits due do not include Child PNC visits.
- [ ] ANC visits due do not include ANC home visits.
- [  Change the color of dashboard cards. All are in red currently.

**Comment by utkarshavni** [comment]
- [ ] All dashboard cards displayed in Green - should be different color.
- [ ] Child PNC is not updated in PNC visits due
- [ ] No. of child deaths count does not get updated.
- [ ] Maternal death count is not updated.

**Comment by AchalaBelokar** [comment]
Unable to enroll in the pregnant program. ![Screenshot 2022-11-07 at 7.23.23 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/6347ee1f-8176-44d9-a8eb-38584b1c5164)

**Comment by AchalaBelokar** [comment]
- [ ]  PNC visits due do not include Child PNC visits.

- [ ]

**Comment by Gojo-Taqi** [comment]
PNC visits due work fine for Child PNC visits, but not for Pregnant beneficiaries
