### ISSUE TITLE
[JSSCP] Offline Dashboard for Senior Health Worker

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#253]
**Motivation:**
The Senior Health Worker (part of NCD user group) requires quick access to list of beneficiaries with details provided below for better monitoring and reporting on the Home page of Avni

**Goal:**
https://docs.google.com/spreadsheets/d/1cLXk9dUHfvyqak1sODnmjKW9xLk87uc3YGTCbkUmpO4/edit#gid=1310915802
The dashboard should display all the indicators provided in sheet and logic written.

- [X] 1.Total number of patients - Disease wise
- [X] 2. No of new enrolled patients - (For the specific week)
- [X] 3. No of deaths - disease wise (For the specific Week)
- [X] 4. No of patients exited from different Disease program - (For the specific Month)
- [X] 5. No of referrals done
- [x] 6. Different due visits - 
- [x] 7. No of cancelled visits -
- [x] 8. No of Completed Visits

**Comment by utkarshavni** [comment]
Following indicators not updated:
- [ ] No of Follow-up visits due
- [ ] No of cancelled visits
- [ ] No of completed visits

**Comment by utkarshavni** [comment]
- [ ] No of Follow-up visits due not updated.

**Comment by AchalaBelokar** [comment]
No of Follow-up visits due not updated.

**Comment by Gojo-Taqi** [comment]
Fixed the Follow up visits due.

**Comment by AchalaBelokar** [comment]
Require a validation date filed

**Comment by Gojo-Taqi** [comment]
Date validation have been added to the follow ups

**Comment by AchalaBelokar** [comment]
You are not fixed it

**Comment by Gojo-Taqi** [comment]
Almost all the cancellation forms didn't have the validation. Added them now
