### ISSUE TITLE
SHG Group Subject Type Registration

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#254]
Create SHG Group subject type.
Location type against which subject to be registered:  Village

SHG Registration form:
https://docs.google.com/spreadsheets/d/1W3TPYyp9F5GS-BHaYvy8eCwUqVdQp9bcHKMBtT-w2G0/edit#gid=310538889

**Comment by AchalaBelokar** [comment]
In the SHG members linked with any livelihood activity from Forest produce, Agriculture these two attributes are not present. According  the requirement  it should be present in the from.![Screenshot 2022-05-16 at 4.05.16 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/73005cc2-7a31-4e78-9668-053df03e3ebf)
