### ISSUE TITLE
[JSSCP]  Cluster Coordinator User Group

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#256]
**Motivation:**
Cluster Coordinator monitors and compiles data for different activities happening at Cluster level. The user group is not there currently in the system for Cluster Coordinator.

**Goal:**
A new user group for Cluster Coordinators should be created who will have permissions for following forms:
Monthly Monitoring Subject Registration form: View and Edit
Village Health Worker Monthly Encounter: View and Edit
Village Health Worker Weekly Encounter: View and Edit
Animal Health Worker Monthly Encounter: View and Edit
Monthly Cluster Monitoring Encounter: View and Edit
No permissions for Senior Health Worker Weekly and Monthly reporting Encounter.

**Acceptance Criteria:**
Cluster Coordinator user should be able to access the forms based on the permissions mentioned above.

**Comment by AchalaBelokar** [comment]
No permissions for Senior Health Worker Weekly and Monthly reporting Encounter.
can edit and feel the data

**Comment by Gojo-Taqi** [comment]
All permissions were allowed to your user. Fixed it now

**Comment by utkarshavni** [comment]
@Gojo-Taqi @AchalaBelokar permissions for perform visit were not enabled in user group permissions - because of which i was not able to see "Do" on the visits to complete the visit. I have enabled them.
