### ISSUE TITLE
Creating Programs for New  Chronic Disease and Enrolment Forms.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#259]
Create Programs for each Chronic Disease mentioned below: The users with access to these forms are part of NCD user groups.
1. Mental Illness
2. Thyroidism
3. Arthritis
4. Cancer
5. COPD
6. Asthma
7. Heart Disease
8. Stroke

Enrolment form links for all Programs:
https://docs.google.com/spreadsheets/d/12JOi_vVqBL394eOq48aJZeisHkR0TQOaLg7xDeNiZeg/edit#gid=243992922

Currently, the monitoring of patients in these programs is not required in app. The follow-ups happen on the ground but recording them in app is not a requirement as of now.

**Comment by AchalaBelokar** [comment]
Date of Diagnosis should be equal or less than current date.
