### ISSUE TITLE
Exit form for New Chronic Disease Programs

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#264]
For all the New Chronic Diseases which have been added, Add Exit form. There is no visit scheduling logic for Exit form as follow-up visits are not required to be recorded in app for these diseases as of now. 

Exit Form Requirements Sheet:
https://docs.google.com/spreadsheets/d/12JOi_vVqBL394eOq48aJZeisHkR0TQOaLg7xDeNiZeg/edit#gid=1951885076

NCD user group will have access to exit beneficiaries from the program.

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-05-17 at 1.37.44 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/fb1f8fc3-a3a6-4708-a5b4-0ff52aa05245)
Date should me less than or equal to current  date

**Comment by AchalaBelokar** [comment]
<img width="728" alt="Screenshot 2022-05-27 at 12 19 35 AM" src="https://user-images.githubusercontent.com/104890488/170556566-899e0fac-fe64-4e34-ac16-3ab3a3e2a4db.png">
<img width="728" alt="Screenshot 2022-05-27 at 12 17 24 AM" src="https://user-images.githubusercontent.com/104890488/170556583-42187b0f-8e6e-45de-9b06-ce15bd0d48fa.png">
Death date should be less than or equal to current  date

**Comment by nupoorkhandelwal** [comment]
@AchalaBelokar Tuberculosis is not part of the NCD program. Please test NCD program exit forms as part of this card.
