### ISSUE TITLE
[App] Monthly Encounter for VHW Report 

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#269]
Create an encounter.

Name: Monthly Village Health Worker Report
Subject type: Monthly Monitoring

Form Link:  https://docs.google.com/spreadsheets/d/1W3TPYyp9F5GS-BHaYvy8eCwUqVdQp9bcHKMBtT-w2G0/edit#gid=2121445953

Add all the fields for which "When to Show" column value is blank. Wherever Weekly is mentioned, those fields will not be added.

Visit scheduling: The visit/encounter should be scheduled on 25th of every month.
https://docs.google.com/spreadsheets/d/1W3TPYyp9F5GS-BHaYvy8eCwUqVdQp9bcHKMBtT-w2G0/edit#gid=2119102511

Overdue visit after 8 days from the scheduled date.

**Comment by arjunk** [comment]
it seems this is blocked because of a platform bug. @vindeolal can you take a look

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-30 at 5 30 21 PM" src="https://user-images.githubusercontent.com/104890488/176672124-f68485be-3145-4eb1-9624-4c4a91121b0b.png">
questions are missing in the above form.

**Comment by utkarshavni** [comment]
@AchalaBelokar also check if visit scheduling is happening correctly for this encounter. It should get scheduled 25th of every month after Monthly Monitoring Subject Registration.

i.e. if Subject is registered before 25th of a month, the encounter should get scheduled on 25th of that month and thereafter it should keep scheduling subsequent visits on 25th of every month.
