### ISSUE TITLE
[App] Senior Health Worker Weekly Reporting Encounter

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#271]
Create a Weekly Encounter for Senior Health Worker Weekly Reporting.

Encounter Name: Senior Health Worker Weekly Reporting
Subject: Monthly Monitoring

Form Link:
https://docs.google.com/spreadsheets/d/1W3TPYyp9F5GS-BHaYvy8eCwUqVdQp9bcHKMBtT-w2G0/edit#gid=27421912

Questions till row no. 41 are for Weekly encounter. Add those for weekly encounter.

**Comment by utkarshavni** [comment]
Putting the card on hold since need to confirm on below given fields. Once confirmed, it will be moved.
1. Week field
2. Dates field
3. Eligible for Fever Study
4. Enrolled in Fever Study
5. Day 7 Interviews conducted

Also need to know if visits can be scheduled on a specific day.

**Comment by utkarshavni** [comment]
Clarifications provided for 1st and 2nd question in previous comment.
Question number 3 to 5 no more required as informed by client - removed from the requirement sheet.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-30 at 4 15 42 PM" src="https://user-images.githubusercontent.com/104890488/176658712-effe213b-66c5-4382-9c10-19708d145764.png">
According  to the excel sheet, last question should not be there in the form
