### ISSUE TITLE
[App] Senior Health Worker Monthly Reporting Encounter

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#272]
Create a monthly encounter.

Name: Senior Health Worker Monthly Reporting Encounter
Subject: Monthly Monitoring

Form Link:
https://docs.google.com/spreadsheets/d/1W3TPYyp9F5GS-BHaYvy8eCwUqVdQp9bcHKMBtT-w2G0/edit#gid=27421912

Check from row no. 43 for questions for this form - add those in the form.

**Comment by AchalaBelokar** [comment]
<img width="387" alt="Screenshot 2022-06-29 at 12 12 12 AM" src="https://user-images.githubusercontent.com/104890488/176258344-c4ed8487-66e7-440a-93a9-a63a5cb38c58.png">

Any epidemic in any of your villages if this question answer  is yes then No of patients treated in the epidemic will show
