### ISSUE TITLE
[JSSCP-Report] Cancelled follow-up visits Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#275]
**Goal**
Create Aggregate Exit report and linked line list to show the count of patients exited from enrollment for specific disease.

**Report Requirements:**
https://docs.google.com/spreadsheets/d/1-URezmmyR7eGKrGmyzcewh68TYBH7wL27IimG-BXVio/edit#gid=1927775088

**Jasper folder:**
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=searchFlow

- [x] Create Aggregate report
- [x] Add filters for Aggregate report
- [x] Create linked linelist
    - [x] Cancelled hypertension follow-ups
    - [x] Cancelled Diabetes follow-ups
    - [x] Cancelled Sickle Cell follow-ups
    - [x] Cancelled Epilepsy follow-ups
    - [x] Cancelled Tuberculosis follow-ups
- [x] Apply filters

**Acceptance criteria**
Cancelled follow-up visits report should show aggregate report as well as line list for the cancelled follow-up encounters.
Date filter should be applicable on Date on which the encounter was cancelled.
Applying filters should populate the data correctly.

- [x] Redo the same in UAT env (since there is no data in the prod)

**Comment by Dinesh2019** [comment]
Test Scenarios :
1. cancel the first follow-up and validate that is reflected in the Jasper report
2. completed the follow-up and validate that is not reflected in the Jasper report after that cancel the second follow-up and validate that is reflected in the Jasper report
3. Cancel the follow-up and validate that is reflecting the Jasper report and after that void the individual and validate that Jasper is not reflecting that individual.
4. edit the individual and check the edit details are reflected as per the user inputs  in Jasper
