### ISSUE TITLE
[JSSCP] Exit Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#279]
**Goal**
Create Aggregate Exit report and linked line list to show the count of patients exited from enrollment for specific disease.

**Report Requirements:**
https://docs.google.com/spreadsheets/d/1-URezmmyR7eGKrGmyzcewh68TYBH7wL27IimG-BXVio/edit#gid=906876076

**Jasper folder:**
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=searchFlow

- [x] Create Aggregate report
- [x] Create linked linelist
- [x] Apply filters

**Acceptance criteria**
Exit Report should show aggregate report as well as line list for the diseases given in requirement. 
Date filter should be applicable on Date of Exit
Applying filters should populate the data correctly.

**Comment by vedfordev** [comment]
time taken : 14 hrs

**Comment by Dinesh2019** [comment]
create the bug card for undoexit scenario handle in the ETL 
https://github.com/avniproject/avni-etl/issues/62
