### ISSUE TITLE
[ETL REPORT] ETL Migration Common reports

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#287]
Save these reports in the JSSCP ETL directory
Update the query here : https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=431825339&range=A1

- [x] Addiction at enrollment
- [x] Analytics (Incedence and Prevalence)
- [x] BMI status enrollment
- [x] Compliance of previous month
- [x] Current BMI status
- [x] No of patients enrolled in program
- [x] Number of patients followed up at different place
- [x] Patient treatment status
- [x] Place of referral
- [x] Reasons for not taking medicines
- [x] Referral reason

Linelist 

- [x] Common linelist
- [x] Patient treatment linelist

**Comment by AchalaBelokar** [comment]
Difference between  old and etl 

- [ ] Analytics (Incedence and Prevalence)

![Screenshot 2023-02-24 at 4.11.33 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/790fe950-a0be-4865-8346-34097a0618fa)



![Screenshot 2023-02-24 at 4.13.58 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/61533bef-0c6d-4978-9d1b-46113acd24fd)

**Comment by AchalaBelokar** [comment]
- [ ] BMI status (Enrollment)

![Screenshot 2023-02-24 at 4.35.51 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/ca17896b-5a47-4b1a-bbca-d4fb0eb311d1)

![Screenshot 2023-02-24 at 4.37.24 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/ee5de125-0a59-444f-b300-95a9cb318e7c)

**Comment by Gojo-Taqi** [comment]
For the report BMI status (enrollment), there is still some point differences. But the data is correct

**Comment by AchalaBelokar** [comment]
- [ ] Place of referral data mismatch with old report....

**Comment by AchalaBelokar** [comment]
- [ ] Disease status of patients on amlodipin mismatch in number:

![Screenshot 2023-04-27 at 11.04.43 AM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/e4ba571b-5460-4b02-b803-67f8a7691573)

**Comment by nupoorkhandelwal** [comment]
1. Place of referral - Fixed the number mismatch, percentage are correct now and not in the old report.
2. Reasons for not taking medicines -

**Comment by BEULAHEVANJALIN** [comment]
AGGREGATES
- [ ] Addiction at enrollment
- [ ] Analytics (Incedence and Prevalence)
- [ ] BMI status enrollment
- [ ] Compliance of previous month
- [ ] Current BMI status
- [ ] No of patients enrolled in program
- [ ] Number of patients followed up at different place
- [ ] Patient treatment status
- [ ] Place of referral
- [ ] Reasons for not taking medicines
- [ ] Referral reason

**Comment by BEULAHEVANJALIN** [comment]
Generic queries:
https://gist.github.com/BEULAHEVANJALIN/e4e46bfce7f3c3c71f82019b6fc67d0e

**Comment by vaijayanthisundaram** [comment]
Addiction at enrolment - new query for hypertension is correct as old didn't consider unique records. Updated new query for diabetes to consider unique records.

**Comment by vaijayanthisundaram** [comment]
Analytics (Incedence and Prevalence)- a difference in death ratio is observed between old and new queries for Tuberculosis. This is due to the program exit reason not being captured in the generic data table (iddv id : 185705 ,162427)

**Comment by vaijayanthisundaram** [comment]
BMI status enrollment - Updated new ETL query. Old query considered enrolment id, when updated to individual
 id matches new query.
Compliance of previous month- inconsistencies in considering latest visits caused mismatch. when both old and ETL queries are updated to consider latest visit, numbers match. Updated ETL query.

**Comment by vaijayanthisundaram** [comment]
No of patients enrolled in program - New ETL query didn't consider unique records. Updated and pushed to ETL.
Number of patients followed up at different place - Old and new ETL queries had inconsistent usage of individual id and enrolment id in diff calculations and on counting unique records. Updated new ETL query and pushed to ETL.

**Comment by vaijayanthisundaram** [comment]
Current BMI status - old query did not consider latest  visit. new ETL query is correct. Pushed to ETL

**Comment by vaijayanthisundaram** [comment]
Patient treatment status - Updated ETL query to consider distinct individual id . Also corrected join condition in final aggregate. pushed to ETL.

**Comment by vaijayanthisundaram** [comment]
Patient treatment status -diff between agg and linelist (of around 1 in same categories) is due to the same patient having two different enrolments for the same program. eg: Individual ids 163617 and 191457 in hypertension and diabetes respectively.

**Comment by Dinesh2019** [comment]
1. Reasons for not taking medicines - date filter (aug1 and oct17)
2. Referral reason date filter (Aug15 - oct17)
3. BMI status enrollment apply filter cluster-shivtarai,age 0-30,gender-male,cast-general )
4. Analytics (Incedence and Prevalence) date filter (April 01- oct17)

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0JKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--859dc8f1c935a66bfdae89ab270616a5f60d2bae/Screenshot%202023-10-18%20at%202.09.26%E2%80%AFPM.png

**Comment by vaijayanthisundaram** [comment]
Above errors are fixed.

**Comment by Dinesh2019** [comment]
Analytics (Incedence and Prevalence)
Feedback in the blank space as we have the value as 0
Screenshot of jasper
 https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVprQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddd696cc5ef0b729d1443948886333eca1b8b54e/Screenshot%202023-10-24%20at%208.53.02%E2%80%AFAM.png

Screenshot of db

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWRrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b67075de65733808328cae7c01e6a6a1c7c20b12/Screenshot%202023-10-24%20at%208.53.49%E2%80%AFAM.png

**Comment by vedfordev** [comment]
please correct the spelling of Incedence to Incidence

**Comment by vedfordev** [comment]
## Notes :

#### Analytics (Incidence and Prevalence)
1. changed spelling of **Incedence** to **Incidence**.
2. In Sex ratio added condition if Null then it shows 0.
3. In sheet updated the query as query has some diffrence.

#### Reasons for not taking medicines
1. In number field add check if null then it shows 0
2. In propotision add check if it is Nan then it shows NA.

**Comment by Dinesh2019** [comment]
BMI Status Enrolment :

Jasper Screenshot :

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d32f1aa0b4738290962817d36bc685760fb6861/Screenshot%202023-11-14%20at%208.55.08%E2%80%AFAM.png

Db report :

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f18cfb1a84b64c488c66b2d6dcb9d6e9fd0a7ab3/Screenshot%202023-11-14%20at%208.55.21%E2%80%AFAM.png

**Comment by Gojo-Taqi** [comment]
Have identified the issue of why the count is not matching when the query is written using generic tables.
It's because of these two lines
```
left join public.group_subject gs on gs.member_subject_id = ind.id
left join jsscp.household house on gs.group_subject_id = house.id
```

Since some individuals are not mapped to households, there is a mismatch in the count.
We cannot remove them since there are filters getting used by households.

**Comment by Gojo-Taqi** [comment]
Moving this back to support ready, as I am in Odisha and have some other stuff to do.

**Comment by AnjaliBhagabati** [comment]
Only the Linelist reports ( Common linelist and Patient treatment linelist) are pending but these two reports are not in frequently use reports list shared by the client (https://docs.google.com/spreadsheets/d/1LZ7bXHO6DoWmoDbV3ENMNWaA0FFVUG0Ku1EaS9CiW_g/edit#gid=648644390)
We can complete the above two reports later once the priority ones are completed.

**Comment by AnjaliBhagabati** [comment]
@vedfordev you can check these P1 :

No of patients enrolled in program
Number of patients followed up at different place
Patient treatment status
Place of referral
Reasons for not taking medicines
Referral reason

**Comment by vedfordev** [comment]
@Dinesh2019 

1. check above report + BMI Status Enrolment. 
2. Old report has some problem. So kindly check with old query. 
3. if jsscp.jsscp_individual_tuberculosis_tb_followup not work then change it with jsscp_individual_tuberculosis_tb_followup_voided294.

**Comment by Dinesh2019** [comment]
- [ ] Patient treatment status in old report getting error SQL Error [42P01]: ERROR: relation "jsscp.jsscp_individual_tuberculosis_tb_followup" does not exist

**Comment by vedfordev** [comment]
@Dinesh2019 check point 3.
