### ISSUE TITLE
[Support]     Moving report to ETL -- Diabetes module

### ISSUE THREAD

**Issue by sachsk** [avniproject/JSSCP#289]
- [x] Disease status fasting

- [x] Disease status HbA1C

- [x] Patients enrol with any existing complication 

- [x] Patients with any new complication

**Comment by AchalaBelokar** [comment]
- [ ] ETL  Disease status fasting report is mismatch with normal  Disease status fasting

- [ ] ETL  Disease status HbA1C report is mismatch  with normal   Disease status HbA1C

- [ ]  ETL Patients enrolled with any existing complications	 no mismatches with Patients enrolled with any existing complications	

1. Proportion 
CVA (Stroke)	
HTN
Neuropathy
TB	
Infection	
Other	
2.  Number	
Neuropathy	
Infection	
Other

**Comment by AchalaBelokar** [comment]
- [ ]   ETL Patients with any new complication number mismatch  with normal report

1. Retinopathy
2. Infection
3. None
