### ISSUE TITLE
[Support]    Moving report to ETL - Epilepsy Module

### ISSUE THREAD

**Issue by sachsk** [avniproject/JSSCP#291]
- [x] Number of patients enrolled with type of disease

- [x] Patients with control over seizure

- [X] Patients with control over seizure linelist

- [x] Children dropped school

- [x] Common linelist

- [x] enrol with physical injury 

- [x] patient using epilepsy diary

- [x] patient with injury during seizures 

- [x] Patients with side effects of drugs

- [x] patient with seizures in last month

- [x] school going children enrolled

**Comment by AchalaBelokar** [comment]
- [ ]ETL  No of patients enrolled with type of disease	no  mismatch with normal No of patients enrolled with type of disease	

1. Focal- motor

**Comment by BEULAHEVANJALIN** [comment]
For *ETL Children dropped school vs normal Children dropped school*, the data in ETL is the correct result. Data on normal Children dropped school is incorrect due to views object not updated for the last few days. So, closing this second point for the same.
