### ISSUE TITLE
[JSSCP] ETL Migration Hypertension

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/JSSCP#293]
Save these reports in the JSSCP ETL directory
Update the query here : 
https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=431825339&range=A1

- [ ] Disease status of patients on amlodipin
- [ ] Hypertension disease status
- [ ] Patients enrolled with any complication
- [ ] Patients on various medicines
- [ ] Patients with any new complications

Linelist

- [ ] Hypertension linelist
- [ ] Patients diagnosed with severe HTN
- [ ] Reduction or increase in blood pressure

**Comment by sachsk** [comment]
@BEULAHEVANJALIN As per sheet this module is already moved to ETL but these reports are not present on jasper please update the status

**Comment by AnjaliBhagabati** [comment]
Closing this since a separate card for P1 is created and @Beula is working on that. Avoiding duplication
