### ISSUE TITLE
[ETL REPORT] ETL Migration MCH report

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/JSSCP#294]
Save these reports in the JSSCP ETL directory

Update Query here: https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=431825339&range=A1

- [ ] ANC - IFA and Calcium Consumption
- [ ] Antenatal services during pregnancy
- [ ] Birth and Death Rates
- [ ] Child Birth
- [ ] Family screening
- [ ] High risk pregnancies with abnormal lab results
- [ ] High risk pregnancy
- [ ] Intranatal Services
- [ ] Patients diagnosed with different types of TB
- [ ] Post Natal Children
- [ ] Post natal mothers
- [ ] Post natal mother services
- [ ] Postnatal Services Child
- [ ] Referral serviecs

LInelist 

- [ ] ANC - IFA and Calcium Consumption Linelist
- [ ] High risk pregnancies with abnormal lab results ( anc clinic ) Linelist
- [ ] High risk pregnancies with abnormal lab results (lab investigation) Linelist
- [ ] High risk pregnancies with abnormal lab results (lab investigation result for pregnancy) Linelist
- [ ] High Risk Pregnancy ANC Clinic and Home Visit Linelist
- [ ] High Risk Pregnancy ANC Clinic Visit Linelist
- [ ] High Risk Pregnancy Enrolment Linelist
- [ ] High Risk Pregnancy First ANC Clinic Visit Linelist
- [ ] Intranatal Services Line list
- [ ] Linelist for ANC Clinic Visit with delivery reported
- [ ] Linelist for Antenatal services 
- [ ] Linelist for child birth details
- [ ] Linelist for mother post natal services
- [ ] Linelist for mother post natal services-delivery
- [ ] Linelist for Post natal children
- [ ] Linelist for post natal mother details
- [ ] Linelist For Postnatal Services Child 
- [ ] referal services abortion Linelist
- [ ] referal services anc Linelist
- [ ] Referral services child Linelist
- [ ] Referral services child referral Linelist
- [ ] Referral services mother Linelist
- [ ] TB line list

**Comment by AnjaliBhagabati** [comment]
Closing this card as we are we are working on ETL cards basis P1 and P2
