### ISSUE TITLE
[JSSCP Phulwari] Changes to Registration & Enrolment forms

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/JSSCP#3]
## Registration Form
**Remove**
 - GPS Coordinates
 - Mohalla
 - Gram Panchayat
**Add**
 - Cluster for JSSCP Area– 
Type of question -Mandatory
List of Cluster - https://docs.google.com/spreadsheets/d/1_33aM0mRhIZyWC9-oxgNxdS73W_yQBgydx1LSFKTIO4/edit#gid=1473836075
- Subcaste – 
Dhurve, Porte, Gandharv, Oraon, Manikpuri, Markam, Satnami, Patel, Jaiswal, Bhaina, DHanuhar, Devangan, Dhruv, Kaivart, Kanvar, Khusaro, Maravi, Rajak, Prajapati, 

## Enrolment form
 - Enrol to – should have the name of the phulwari worker as in JSSCP the phulwari is known after the name of the phulwari worker 

## Address hierarchy is in this excel: 
https://docs.google.com/spreadsheets/d/1_33aM0mRhIZyWC9-oxgNxdS73W_yQBgydx1LSFKTIO4/edit#gid=1473836075

#### Scheduling Scenarios - 
- Growth Monitoring 
                    - On Enrollment - On the same day
                    - Second Visit onward - Next month onwards the given date in Enrolment 'Phulwari Visit Date'
                    - On Cancel - Schedule the visit on the same date in next month (Do nothing if the kid is exited 
                       from the program)
                      For Eg: Phulwari Visit Date - 16th 
                      Enrolment date - 27 Dec 2019
                      First Growth Monitoring - On the day of Enrolment (27-Dec-2019)
                      Second  Growth Monitoring - 16 Jan 2020
                      Third Growth Monitoring - 16 Feb 2020 
                        and so on.
- On Albendazole Feb - Schedule Albendazole Aug
- On Cancel Albendazole Feb- Schedule Albendazole Aug (Do nothing if the kid is exited from the 
   program)
- On Albendazole Aug -  Schedule Albendazole Feb
- On cancel Albendazole Aug - Schedule Albendazole Feb (Do nothing if the kid is exited from the 
   program)

**Comment by garimadosar5** [comment]
QA Notes - 

- Subcaste -  Put Other at the end of the list.
-
