### ISSUE TITLE
[JSSCP] Change in medicine is not reflecting in subsequent visits in Hypertension program

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#303]
Support ticket - https://avni.freshdesk.com/a/tickets/2526

There are screen recordings in the ticket itself. Still steps to reproduce the issue are --

1. Enrol an individual to Hypertension program, select Amlodipin medicine and its strength and time
2. Complete the Hypertension Followup -1  visit, and change the medicine , add another medicine say Amlodipin and Enalapril
3. Complete the next Hypertension Followup -2 and select Continue same medicine, and the app still shows the medicine prescribed in the enrolment and not from the last followup.

- [x] Need to fix the above issue, ideally the medicines from Hypertension Followup -1 should have populated in the Hypertension Followup -2 .

- [x] Need to check same for other NCD programs as same logic was implemented there as well

**Comment by BEULAHEVANJALIN** [comment]
programEncounter has no such method called **findObservationValueInEntireEnrolment** with a **checkin enrollment** parameter. Due to this it is difficult find observation only in latest encounter. 
So moving this card on hold. The methods in programEncounter needs to be refactored further again.

**Comment by BEULAHEVANJALIN** [comment]
- [ ] Register a subject
- [ ] Enrol to a program (Hypertension, Diabetes, Sickle cell, Epilepsy), Note down the medicine selected and the dosage
- [ ] Go for an encounter. If continue same medicine, then decision should show the same medicine and its dosage based on latest medicine selected.
