### ISSUE TITLE
JSSCP Report ETL Migration

### ISSUE THREAD

**Issue by sachsk** [avniproject/JSSCP#304]
List of reports which client is using frequestly: https://docs.google.com/spreadsheets/d/1LZ7bXHO6DoWmoDbV3ENMNWaA0FFVUG0Ku1EaS9CiW_g/edit#gid=648644390

those which are highlighted with Yellow color are to be shifted to ETL

**Comment by salilsamanvay** [comment]
Since we are not clear on which reports are being used, details are awaited from Client. putting this epic on hold.

**Comment by AnjaliBhagabati** [comment]
Need to analyse the new report requirement and bifurcate the report requirements into
New Forms
Change in form request
ETL Migration Report

**Comment by AnjaliBhagabati** [comment]
Have started working on it

**Comment by AnjaliBhagabati** [comment]
Have created a master reports status database for JSSCP all reports and have put the status and priority (based on client's frequently used marking sheet : https://docs.google.com/spreadsheets/d/1LZ7bXHO6DoWmoDbV3ENMNWaA0FFVUG0Ku1EaS9CiW_g/edit#gid=648644390) in this sheet.

Master Report Status Sheet Link: https://docs.google.com/spreadsheets/d/110abTQ-685LlptvntVb7DjQTSdh9vzCdLgtMH08MFmY/edit#gid=406344359
