### ISSUE TITLE
[JSSCP] Disease prevalence report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#307]
**Use case**
The purpose is for the program team members to look at the different indicators such as incidence, prevalence and death rate for specific diseases in the population.

Report requirements:
https://docs.google.com/spreadsheets/d/1-URezmmyR7eGKrGmyzcewh68TYBH7wL27IimG-BXVio/edit#gid=982085083

- [x] Aggregate Report
- [x] Linked linelist for the prevalence count

**Comment by Dinesh2019** [comment]
@BEULAHEVANJALIN need UAT org in jasper for this account
