### ISSUE TITLE
[JSSCP] TB Followup

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#31]
https://docs.google.com/spreadsheets/d/1FB29IqJ-afqWk7OnYSAfTiMXUTYlp8vXwcg6gImW-gk/edit#gid=1458980048&range=A1

**Comment by sachsk** [comment]
On hold due to
Needs some changes in the enrolment form.

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 
Question - Size of the lymph node. This should depend on the enrolment form. If this is filled in enrolment. Please check and fix if needed.
