### ISSUE TITLE
[JSSCP] New Diagnosis Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#313]
**Goal**
Create Aggregate report and linked line list to show the count of patients diagnosed for specific disease.

**Report Requirements:**
https://docs.google.com/spreadsheets/d/1-URezmmyR7eGKrGmyzcewh68TYBH7wL27IimG-BXVio/edit#gid=0

**Jasper folder:**
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=searchFlow

- [x] Create Aggregate report
- [x] Create linked linelist
- [x] Apply filters

**Acceptance criteria**
Report should show aggregate report as well as line list for the diseases given in requirement. 
Date filter should be applicable on Date of Diagnosis.
Applying filters should populate the date accordingly.

**Comment by vedfordev** [comment]
### Reports :

__- Aggregate Report:__
    1. New Diagnoses Report
 
__- LineList Report:__  
    1. Linelist for Hypertension diagnosis report
    2. Linelist for Diabetes diagnosis report
    3. Linelist for Sickle Cell diagnosis report
    4. Linelist for Epilepsy diagnosis report
    5. Linelist for Tuberculosis diagnosis report

**Comment by vedfordev** [comment]
time to complete : 8-9 hours
