### ISSUE TITLE
[JSSCP] New Diagnosis report for New Chronic Diseases

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/JSSCP#315]
**Goal**
Create Aggregate report and linked line list to show the count of patients diagnosed for specific disease along with the category of disease.

**Report Requirements:**
https://docs.google.com/spreadsheets/d/1-URezmmyR7eGKrGmyzcewh68TYBH7wL27IimG-BXVio/edit#gid=1120534174

**Jasper folder:**
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=searchFlow

**Aggregate Report task** :

- [x] Format (create dataset, alignments, title changes and other format stuff)
- [x] Mental Illness and subcategory
- [x] Arthritis
- [x] Thyroidism and subcategory
- [x] Cancer and subcategory
- [x] COPD
- [x] Asthama
- [x] Heart Disease and subcategory
- [x] Stroke
- [x] Apply Filter

**LineList Report task**

- [x] Mental illness Report
- [x] Arthritis Report
- [x] Thyrodism Report
- [x] Cancer Report
- [x] Copd Report
- [x] Asthama Report
- [x] Heart Disease Report
- [x] Stroke Report
- [x] Create and Apply Filter 
- [x] Apply link to avni 

**Finishing task**

- [x] Dynamic Where
- [x] Aggreagate report link to linelist
- [x] Moving Report to UAT

  

**Acceptance criteria**
New Diagnosis Report should show aggregate report as well as line list for the diseases given in requirement. 
Date filter should be applicable on Date of Diagnosis.
Applying filters should populate the date accordingly.

**Comment by vedfordev** [comment]
### Developer's Note :
---
@utkarshavni  As Discuss with @nupoorkhandelwal there is no need for create linelist report for disease category wise. If we create then count will come around 29 linelist. Rather than doing that we can provide dynamic where in aggregate report and provide Type of disease filter in linelist. If we do this step then count of linelist comes around  7.

**Comment by vedfordev** [comment]
@utkarshavni @Dinesh2019 @nupoorkhandelwal For many disease **type of disease** is multi select value. So if you do summation of type of disease and match with total count of that disease, It may be differ.

**Comment by vedfordev** [comment]
@Dinesh2019  undo exit scenario will not work as you raised bug:
https://github.com/avniproject/avni-etl/issues/62

**Comment by Dinesh2019** [comment]
@utkarshavni @vedfordev closing this card since we don't have any issue related to the card but we have the issue where old reports are removed from the UAT env.
