### ISSUE TITLE
JSSCP reports UAT feedback as of 5th Oct 2023

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/JSSCP#319]
Feedback captured during showcase call held on 5th Oct with Ravindra:
below document has feedback page as well along with report requirement format:
https://docs.google.com/spreadsheets/d/1-URezmmyR7eGKrGmyzcewh68TYBH7wL27IimG-BXVio/edit#gid=431017667

- [x] **Cancelled Follow-up Visits report** - Reports showing count 0 for all the programs, in order to fix it update the queries to pick cancel date time from respective followup cancel ETL tables.

------------------------------------------------------------------------------------------------------------------------

**NO ACTION TO BE TAKEN BY DEV -**

- [ ] **Disease Prevalence report**: This report has too many difference between requirement document, Jasper reports and client expectation. what we have agreed is Ravindra is process of drafting new report requirement in which they will share all the modifications which they need for this report and we can rebuilt this report. for now he will accept this report as is.

- [ ] **New Diagnosis for New chronic diseases**: Its already there under respective folder, Salil to confirm on this if there is really a need to merge all the indicators under one report.

**Comment by salilsamanvay** [comment]
Ravindra will start testing these reports, he will share his feedback. meanwhile we can correct above mentioned first 2 report.

**Comment by Gojo-Taqi** [comment]
There is less data in ETL tables compared to generic tables.

**Comment by Gojo-Taqi** [comment]
Created a ticket regarding the issue
https://avni.freshdesk.com/a/tickets/3163

**Comment by salilsamanvay** [comment]
@sachsk please add next steps to clean data (ETL vs Generic mismatch)

**Comment by sachsk** [comment]
To fix the ETL issue delete the org schema and regenerate the ETL table.

**Comment by Gojo-Taqi** [comment]
@Dinesh2019 moving this card back to QA ready as the counts have now been fixed on the ETL tables.
Note:- Some individuals(45 in number) are part of multiple households, due to which they are coming in the hypertension cancelled followup multiple times.
