### ISSUE TITLE
JSSCP Priority 1 (P1) ETL Migration Epilepsy

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/JSSCP#325]

**Comment by AnjaliBhagabati** [comment]
Below are the list of Priority 1 (P1) ETL Migration Reports to be done for the Epilepsy Program
Whoever is working on it, kindly update the status as Completed in the Report To ETL sheet:
Kindly Update "Completed" status here: https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=431825339

**Comment by adamsanadi6** [comment]
@AnjaliBhagabati ETL migration is already completed for this Epilepsy program by @sachsk .

**Comment by adamsanadi6** [comment]
Since this was already done. I'm closing the card.
