### ISSUE TITLE
JSSCP Priority 1 (P1) ETL Migration TB

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/JSSCP#327]

**Comment by AnjaliBhagabati** [comment]
- [ ] Patients diagnosed with different types of TB (Program: TB)
- [ ] Patients diagnosed with extrapulmonary TB with different types (Program: TB)
- [ ] Patients who are on different phases of treatment with any side effects (Program: TB)
- [ ] TB family screening (Program: TB)
- [ ] TB patients with any new comorbidity (Program: TB)

**Comment by adamsanadi6** [comment]
- For the following three tasks, queries in ETL, drill down, and the respective Linelist (with the query changed in ETL) have been completed.
1. Patients diagnosed with different types of TB (Program: TB)
2. Patients diagnosed with extrapulmonary TB with different types (Program: TB)
3. Patients who are on different phases of treatment with any side effects (Program: TB)
- For TB family screening (Program: TB) only Query has been changed to etl.(drill down and linelist is pending)
- For TB patients with any new comorbidity (Program: TB) nothing has been done so far.

**Comment by Dinesh2019** [comment]
- [ ] Patients diagnosed with different types of TB (Program: TB)

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbcdf19680f1b366f098d36438ae7434d95cb08f/Screenshot%202024-03-03%20at%206.31.02%E2%80%AFPM.png" alt="Screenshot 2024-03-03 at 6.31.02 PM.png" />

**Comment by Dinesh2019** [comment]
- [ ] Getting errors for Patients who are in different phases of treatment
with any side effects

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6782313fcd7c58c696951820a97126473189ebd8/Screenshot%202024-03-04%20at%208.09.51%E2%80%AFAM.png" alt="Screenshot 2024-03-04 at 8.09.51 AM.png" />
