### ISSUE TITLE
JSSCP Priority 1 (P1) ETL Migration TB#327

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/JSSCP#342]

**Comment by AnjaliBhagabati** [comment]
Below are the list of Priority 1 (P1) ETL Migration Reports to be done for the Hypertension
Whoever is working on it, kindly update the status as Completed in the Report To ETL sheet:
Kindly Update "Completed" status here: https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=431825339

- [ ]  TB family screening (Program: TB)
- [ ]  TB patients with any new comorbidity (Program: TB)

**Comment by Dinesh2019** [comment]
- [ ] TB patients with any new comorbidity (Program: TB) we have the data mismatch

**Comment by adamsanadi6** [comment]
@Dinesh2019 
[ ] There was a count mismatch in the linelist and the aggregate of 'TB family screening (Program: TB)' due to the dynamic WHERE clause not being updated to ETL.

**Comment by Dinesh2019** [comment]
- [ ] Getting this count mismatch after applying the filter 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3F1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f2bbb69b7ddc85be22d2783a686658ff278d041/Screen%20Recording%202024-03-05%20at%209.48.10%E2%80%AFAM.mov
