### ISSUE TITLE
Report data source correction

### ISSUE THREAD

**Issue by sachsk** [avniproject/JSSCP#343]
## Context
In the new ETL report we have used data source from the old directory (JSSCP), but we should not use the data_sources from different directory so as a part of this card we have to change the data source of the reports present in the JSSCP(ETL) directory.

## Task

- [x] Check the data source of report present in the JSSCP (ETL) directory if its from different directory (JSSCP) change it to the JSSCP (ETL)

**Comment by Dinesh2019** [comment]
- [ ] getting the error in TB aggregate -- > Treatment --->  completed clicking on the count getting the below error 

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e4ba7f9e76d72e73d42547aa8bd964dec90cd2b/Screenshot%202024-03-28%20at%205.43.53%E2%80%AFPM.png" alt="Screenshot 2024-03-28 at 5.43.53 PM.png" />

**Comment by sachsk** [comment]
@Dinesh2019 this report is not migrated to ETL and uses the old view so it will not work, you can move this card.
