### ISSUE TITLE
Fix rule failure with uuid "591b1009-ac31-403f-bfba-1b4c5f231e4e"

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/JSSCP#345]
Link to the report [here](https://reporting.avniproject.org/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6ImNhcmRfXzU0MiIsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsInJ1bGVfdXVpZCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIjU5MWIxMDA5LWFjMzEtNDAzZi1iZmJhLTFiNGM1ZjIzMWU0ZSJdLFsiPSIsWyJmaWVsZCIsIm9yZ2FuaXNhdGlvbiIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIkpTU0NQIl1dLCJvcmRlci1ieSI6W1siZGVzYyIsWyJmaWVsZCIsImVycm9yX2RhdGVfdGltZSIseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoifV1dXX0sInR5cGUiOiJxdWVyeSIsImRhdGFiYXNlIjo1fSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpudWxsLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InBpdm90X3RhYmxlLmNvbHVtbl9zcGxpdCI6eyJyb3dzIjpbWyJmaWVsZCIsIm9yZ2FuaXNhdGlvbiIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sWyJmaWVsZCIsInJ1bGVfdXVpZCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dLCJjb2x1bW5zIjpbXSwidmFsdWVzIjpbWyJhZ2dyZWdhdGlvbiIsMF1dfSwicGl2b3RfdGFibGUuY29sbGFwc2VkX3Jvd3MiOnsidmFsdWUiOlsiW1wiSUhNUFwiXSIsIltcIkpOUENUXCJdIiwiW1wiQXNod2luaVwiXSIsIltcIkxlbmQgYSBIYW5kIEluZGlhXCJdIiwiW1wiQVBGIE9kaXNoYVwiXSIsIltcIkpTUyBTaW5ncmF1bGlcIl0iLCJbXCJHREdTR09NIFVBVFwiXSIsIltcIklQSCBDVFJJVEggVUFUXCJdIiwiW1wiUldCIE5JVEkgQWF5b2cgVUFUXCJdIiwiW1wiTGVuZC1hLWhhbmQtaW5kaWEgVUFUXCJdIiwiW1wiSVBIIE1EQVQgVHJpYWxcIl0iLCJbXCJJUEggU0NEIFVBVFwiXSIsIltcIklITVAgVFJBSU5JTkdcIl0iLCJbXCJNb2JpbGUgQ3JlY2hlc1wiXSIsIltcImh1bGRlbW9cIl0iLCJbXCJiZXVsYWggdGVzdFwiXSIsIltcIlBvV0VSXCJdIl0sInJvd3MiOltbImZpZWxkIiwib3JnYW5pc2F0aW9uIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSxbImZpZWxkIiwicnVsZV91dWlkIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV19fSwib3JpZ2luYWxfY2FyZF9pZCI6MjcyM30=)

- [ ] Have bundles of both the orgs downloaded as backups.
- [ ] Upload bundle to uat
- [ ] Fix the rule in the pregnancy enrolment form for the element "Is women registered within 3 months".
- [ ] Paste the faulty code and the fix deployed to fix the code after fixing
- [ ] Close all the logs with this uuid in production after deploying changes.

**Comment by BEULAHEVANJALIN** [comment]
The `motherCalculations` in `avni-health-modules` expects `lastMenstrualPeriodConceptName` to compute gestational age. Although our code doesn't directly use this concept, this is erroring out because it expects a date lmp (which is undefined). So added a simple check to do the calculation only when LMP date exists.

**Comment by BEULAHEVANJALIN** [comment]
Old script:
```
"use strict";
({params, imports}) => {
    const programEnrolment = params.entity;
    const formElement = params.formElement;
    // const lmpDate = programEnrolment.getObservationValue('Last menstrual period');
    const value = 
imports.motherCalculations.currentTrimester(programEnrolment,programEnrolment.enrolmentDateTime);
    var isRegisterredWithinThreeMonths;
  if(value > 1)
    isRegisterredWithinThreeMonths = 'No'; 
  else 
    isRegisterredWithinThreeMonths = 'Yes';
    
    return new imports.rulesConfig.FormElementStatus(formElement.uuid, true, isRegisterredWithinThreeMonths);
};
```

---

Updated script:
```
'use strict';
({params, imports}) => {
  const programEnrolment = params.entity;
  const formElement = params.formElement;
  let value = null;
  const condition11 = new imports.rulesConfig.RuleCondition({programEnrolment, formElement}).when.valueInEnrolment("814f1780-aa3d-4c46-b881-71face696220").defined.matches();
  if(condition11 ){
    const currentTrimester = imports.motherCalculations.currentTrimester(programEnrolment,programEnrolment.enrolmentDateTime);
    value = currentTrimester > 1 ? 'No' : 'Yes';
  }
  return new imports.rulesConfig.FormElementStatus(formElement.uuid, true, value, [],[]);
};
```

**Comment by BEULAHEVANJALIN** [comment]
[JSSCP.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODg1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba192b780a5f8d87b9a52c98a28db7a218a3d9e5/JSSCP.zip)
[JSSCP UAT NEW.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVk1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--509817793d9b6f52af727fc7c00f3803f369d195/JSSCP%20UAT%20NEW.zip)

**Comment by BEULAHEVANJALIN** [comment]
Uploaded the UAT bundle to prod on April 8th
