### ISSUE TITLE
[JSSCP] Pregnancy Enrolment

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#35]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=534785871

**Comment by garimadosar5** [comment]
QA Notes - 
-  Question "High-Risk conditions in previous pregnancy" NO HIGH-RISK CONDITION should be a unique answer.
-

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=534785871. Please look in this requirement sheet. I guess the link above was pointing the old sheet.

**Comment by garimadosar5** [comment]
QA Notes - 2
- If woman does not want to continue the pregnancy, it should schedule the abortion form but it is scheduling ANC visit.
![Screen Shot 2020-05-05 at 11.42.56 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/eae433ce-7729-413d-9b75-1c6aa130ed92)

**Comment by garimadosar5** [comment]
QA Notes - 3
- Questions -
1. Death
2. Death of children within 1 week after delivery
3. Death of children due to congenital abnormality
are not there in the encounter form.
-
