### ISSUE TITLE
[JSSCP] ANC Clinic Visit

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#36]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=1132231519

**Comment by garimadosar5** [comment]
QA Notes - 
- We can add BMI also in ANC visits, it is not given in the sheet but we can add it is easier to understand if the woman is underweight or not.
-

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 Q 19 and 20 are high risk conditions mentioned that we need to display at the end of ANC encounters and enrollment respectively

**Comment by garimadosar5** [comment]
QA Notes - 

- Question Abdominal check. Please add None option.
![Screen Shot 2020-05-08 at 11.15.23 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c1c680c7-87d5-44a5-b3d6-04009ca19bd0)
