### ISSUE TITLE
[JSSCP] Delivery Form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#37]
https://docs.google.com/spreadsheets/d/1IQPxrh3WAB6gxobUR3Xmp__H4kFsy3yi1ZQdnnfDUOM/edit#gid=711406613

**Comment by garimadosar5** [comment]
QA Notes- 
- If place of delivery OTHER selected, Text field is not showing.
-

**Comment by arjunk** [comment]
Moving this to QA Failed as we are seeing some Rule Failure Telemetry messages.

**Comment by nupoorkhandelwal** [comment]
Changes made in JSSCP UAT --

1.Program Encounter Cancellation Form
2. Pregnancy program summary
3. ANC Clinic and home visit schedule rule
4.Delivery form visit schedule 
5. Delivery form Gestational age filed view filter.


These changes are related to the the rules failing on production and UAT.


@garimadosar5 We would need to pair on this to test .
