### ISSUE TITLE
[JSSCP Phulwari][Report] Z-score (Weight for Age) of Children for First weight and Last weight

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#39]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=186338417

##### Ref Doc - https://drive.google.com/drive/folders/1-BWI8gnsrYF8UOIcj6xxlLUcV5EKyQWx

**Comment by vindeolal** [comment]
https://reporting.openchs.org/question/770
https://reporting.openchs.org/question/771
