### ISSUE TITLE
[JSSCP Phulwari][Report] Comparison between first and last weight of Children

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#40]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=186338417

**Comment by vindeolal** [comment]
https://reporting.openchs.org/question/750

**Comment by garimadosar5** [comment]
QA Notes - 
- Number of children in first weight and last weight is same or not?

**Comment by vindeolal** [comment]
- Number of first weight and last(latest) weight children count is same. (added children count column,)
- If weight is taken only once it get counted in both first weight and latest weight. (If we don't do it then count of children will differ).
- Children count column added.
