### ISSUE TITLE
[JSSCP Phulwari][Report] WFA SD % Group wise (Male/Female)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#41]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=186338417

- All Gender Children (First weight)	
- Male Children (First weight)				
- Female Children (First weight)	
- All Children (Last weight)	
- Male Children (Last weight)	
- Feale Children (Last weight)

**Comment by vindeolal** [comment]
https://reporting.openchs.org/question/758
https://reporting.openchs.org/question/759

**Comment by garimadosar5** [comment]
QA Notes - 
- Total children currently in Phulwari program is not 994. There are more children in the program. Please check once.

**Comment by vindeolal** [comment]
@garimadosar5 
- Total children are 1021.
- No it doesn't include <-3SD cases in <-2SD column.
- In requirements there is no line list report attached. If we need one what all columns we need in that report?

**Comment by vindeolal** [comment]
Added line listing reports
