### ISSUE TITLE
[JSSCP Phulwari][Report] Z-score (Weight for height) of Children for First weight/height and Last weight/height	

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#42]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=186338417

**Comment by vindeolal** [comment]
https://reporting.openchs.org/question/772
https://reporting.openchs.org/question/773
