### ISSUE TITLE
[JSSCP Phulwari][Report] Weight for Height SD % - Male/Female children

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#43]
https://docs.google.com/spreadsheets/d/1Wcj5WiF3FdtdLshdJNXlPDp7rMWrd9yszkDu8uAItu4/edit#gid=186338417

- All Gender Children (First weight for height)
- Male Children (First weight for height)
- Female Children (First weight for height)	
- All Gender Children (Last weight for height)	
- Male Children (Last weight for height)	
- Female Children (Last weight for height)

**Comment by vindeolal** [comment]
https://reporting.openchs.org/question/760
https://reporting.openchs.org/question/761

**Comment by garimadosar5** [comment]
QA Notes - 
- Total children currently in Phulwari program is not 994. There are more children in the program. Please check once.
- In the column <-2SD, it includes <-3SD cases also?
- Should we add the line list here also as we are doing it for all the aggregate reports?

**Comment by vindeolal** [comment]
Added line listing reports
