### ISSUE TITLE
[JSSCP][Report] Antenatal Services

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#44]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=96095858

**QA Checklist -** 
- [ ] Percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] All the filters are there.
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are, as mentioned in the requirement sheet.
- [ ] cases are pointed to UAT.

**Comment by nupoorkhandelwal** [comment]
Moving this card to on hold. Will continue after moving Ashwini to prod.

**Comment by nupoorkhandelwal** [comment]
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FJSSCP%2FReports%2FAggregates&reportUnit=%2FJSSCP%2FReports%2FAggregates%2FAntenatal_services_during_pregnancy&standAlone=true
