### ISSUE TITLE
[JSSCP] ANC Home Visit

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#46]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=2081054628

**Comment by garimadosar5** [comment]
QA Notes - 
- Question "Mosquito Net given", skip logic is not working.
- Add new questions highlighted in YELLOW.
- What is qua 19 and 20? How are we showing these questions?

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  

Question -
"Did mother found with pregnancy-induced disease?" - this question shows in every visit, second visit onwards, even once user has selected that woman had Diabetes or hypertension. (in logic it is given that stop showing once it is confirmed.)

This question has been removed now.
