### ISSUE TITLE
[JSSCP] USG Report

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#47]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=110785783

**Comment by garimadosar5** [comment]
QA Notes - 
- for the questions 
1. Foetus is ok
2. Presentation of baby
3. Twin baby
if the answer is any high-risk condition then it should show at the end.
Check this once, we can ignore if not required.

**Comment by garimadosar5** [comment]
QA Notes - 2
- Feotus presentation is 'Breach', that is high risk condition according to Observation Table but it is not showing in High risk conditions. Please check.
 ![Screen Shot 2020-05-06 at 7.33.51 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/cb69cd06-c987-46dc-bb2a-8f60351a443d)

**Comment by garimadosar5** [comment]
QA Notes- 
- Feotus presentation question is being asked in USG report as well as ANC clinic. We should ask it in one form only.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 Yes, they will be capturing position in both visit, ie.  ANC Clinic and USG.
