### ISSUE TITLE
[JSSCP] Lab Investigations

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#48]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=671699279

**Comment by garimadosar5** [comment]
QA Notes - 
- 'Not Done' option is not there, for ant of the questions.
- Hb electrophoresis should be shown only if the sickle prep is positive.
- Include yellow highlighted point for the last two questions (RBS and Glucose test)

**Comment by nupoorkhandelwal** [comment]
@sachsk  There are changes in Lab investigation form plz check.
