### ISSUE TITLE
[JSSCP] Create Users

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#5]
### Deploy it through AdminUI.

https://docs.google.com/spreadsheets/d/1_33aM0mRhIZyWC9-oxgNxdS73W_yQBgydx1LSFKTIO4/edit#gid=746835886

#### [UsersAndCatchments file here](https://docs.google.com/spreadsheets/d/1_33aM0mRhIZyWC9-oxgNxdS73W_yQBgydx1LSFKTIO4/edit#gid=914194411). Some user's info missing which will be provided later. 

- All the users should have spinner type calender.
- No GPS
- Hindi Language

**Comment by sidsamanvay** [comment]
Waiting for user info. until then put on hold
