### ISSUE TITLE
[JSSCP] Child Vaccination Form and Checklist

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#50]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=867047100

https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=1585262184

**Comment by garimadosar5** [comment]
QA Notes - 
- Vaccination checklist option is not there.
![Screen Shot 2020-05-04 at 12.56.32 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/5188ec93-4799-43e0-afb6-4ce42e382da5)

**Comment by garimadosar5** [comment]
QA Notes- 
- Pentavalent 3 is showing in expire. Case - Sindhu Pant
![Screen Shot 2020-05-08 at 3.54.51 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a1c02853-ae0e-40f3-bdaa-46cc20224a08)
