### ISSUE TITLE
[JSSCP] Program Summary for Mother program

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#52]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=2091698935

**Comment by garimadosar5** [comment]
QA Notes - 
- Program Summary is not showing. (Case - Kamal Kumar)
![Screen Shot 2020-05-04 at 12.58.01 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ed85fa57-f4c3-418e-95c6-e4ece2507bcb)

**Comment by garimadosar5** [comment]
QA Notes - 2
- BP is not showing in Program Summary.
