### ISSUE TITLE
[JSSCP] Abortion Followup

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#53]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=863682445

**Comment by garimadosar5** [comment]
QA Notes - 
- for question - "How many times a day does mother change the clothes?" logic is not implemented - it says number 1-9 but I can fill any number.
-
