### ISSUE TITLE
[JSSCP] Birth Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#54]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=765607205

**Comment by garimadosar5** [comment]
QA Notes - 
- The question "Diagnosis of the baby immediately after birth" - We will not enrol baby if that is a stillbirth. So we might want to remove that option. Check once.
- Questions - 
1. If baby was not breathing for 30 seconds, was any action taken?
2. Was mucus extractor used?
3. What was the outcome of action? 
are not there in the form.

**Comment by nupoorkhandelwal** [comment]
@sachsk "Diagnosis of the baby immediately after birth" >> remove the answer option of Stillbirth.

@garimadosar5  Birth form will be planned visit. So the scheduled form should work fine.
