### ISSUE TITLE
[JSSCP] Child PNC

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#55]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=1896792459

**Comment by garimadosar5** [comment]
QA Notes - 
- Question - "TIme of Breastfeeding", we are taking only time but what if Breastfeeding was not done on the same day as birth? We should take date also. Check once.
- Question - "How was breastfeeding", in logic it says show counselling point but we do not have any counselling points and also when to show counselling points.
- Question - "Temperature of baby", Unit is (F) but everywhere else we have taken unit Celsius. check once. I guess they use electronic one and it gives the temperature in celsius.
- And in temperature, we do not have option to say "Don't know".
- "General counselling points" are not showing at the end.
- Also, there are some counselling points given with the question.
