### ISSUE TITLE
[JSSCP] Child Enrolment

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#56]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=887333461

**Comment by garimadosar5** [comment]
QA Notes - 
- What is Dummy in Enrolment form?
![Screen Shot 2020-05-04 at 11.38.20 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f8c0c8ef-fbd9-4f4d-9253-a62ad9583a41)

**Comment by sachsk** [comment]
removed.
