### ISSUE TITLE
[JSSCP] Mother PNC

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#57]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=1610300197

**Comment by garimadosar5** [comment]
QA Notes-
 - Question "Refer the mother immediately to hospital. Did arrangement was made?" is not showing.
-

**Comment by garimadosar5** [comment]
QA Notes - 
- In counselling tips - 
"Keep baby warm" point is not there.
