### ISSUE TITLE
[JSSCP] Registration Form 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#58]
https://docs.google.com/spreadsheets/d/1IQPxrh3WAB6gxobUR3Xmp__H4kFsy3yi1ZQdnnfDUOM/edit#gid=406612277[](url)

**Comment by garimadosar5** [comment]
QA Notes - 
- Socio-economic details are extra in reg form. (not there in requirement sheet)
- Just check once if "Caste" and "Category" questions are showing the expected options.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 Socio-economic details were already there (May be in the Phulwari registration).
Same for caste and category values. If there is any requirement doc of the phulwari registration please share, so that we can confirm.
