### ISSUE TITLE
[JSSCP] Mother Visit Scheduling

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#59]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=2119102511

**Comment by garimadosar5** [comment]
QA Notes - 
- Delivery form is not scheduling. Case - (Smita ash)
-

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  

For point>>

If I am cancelling AV+CN clinic visit, it schedules both ANC clinic and ANC Home visit. - Case (Preg e)
There were one ANC clinic (07 May 2020) and one ANc home visit (11 Jun2020) were there. Now I wanted to cancel only Clinic visit. when I cancelled the ANC clinic visit it asks next ANV visit date. Given date (13 Jul 2020). Now I have one ANC clinic visit (13 Jul 2020) and one ANC home visit (13 Jul 2020). How will I perform ANC Home visit for 11 Jun 2020. 

I am not clear what exactly is the scenario u want to test.

Ideally if one cancels an ANC Clinic visit (eg.scheduled for 7th May), then two visits get scheduled, viz. ANC Clinic Visit (for the date selected during the visit)  and ANC Home VIsit for the same date of the current encounter (ie. 7th May).
