### ISSUE TITLE
[JSSCP] Chid Visit Scheduling

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#60]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=2119102511

**Comment by garimadosar5** [comment]
QA Notes - 
- If in PNC form question "Child Died" is YES then do to schedule any PNC.
-
