### ISSUE TITLE
[JSSCP] Epilepsy Porgram Summary

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#64]
https://docs.google.com/spreadsheets/d/1nCI079lBmUzNUA4KOB3fdMn7nz7EKVc6sk8RLycL56w/edit#gid=2091698935

**Comment by garimadosar5** [comment]
QA Notes - 
- Program summary is not showing up until the followup form is filled.
It is not taking value from Enrolment form. (whatever is available).

**Comment by sachsk** [comment]
"injury during seizure" is now taking value from enrolment as well as follow-up.
rest are taking from follow-up.
