### ISSUE TITLE
[JSSCP] Tuberculosis Program Summary

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#66]
https://docs.google.com/spreadsheets/d/1FB29IqJ-afqWk7OnYSAfTiMXUTYlp8vXwcg6gImW-gk/edit#gid=1869779516

- All the Indicators and its calculation is present in the sheet.

**Comment by sachsk** [comment]
on hold 
need to discuss some points.

**Comment by garimadosar5** [comment]
QA Notes-  
![Screen Shot 2021-01-14 at 6.22.16 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/d7d1a595-c54c-429e-8912-af897e33197c)
- Drugs value is not showing.
- We are changing Lab test result form so values in program summary will also change. like Drug-resistant
 and New comorbidity - RBS, ALT, HIV,

**Comment by garimadosar5** [comment]
QA Notes 2 - 
- Drugs should be comma seperated
- And for weight and BMI, seperator are there. But values are not available yet.
![1610688999407.JPEG](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/47a9804c-0627-4c56-ba05-b959841d06ed)
