### ISSUE TITLE
[JSSCP] [UAT Feedback] Registration Form Changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#67]
https://docs.google.com/spreadsheets/d/12la2xgJBcWn9hwxzwbC9tq1N6RPpjUHKp_WNph1aYnE/edit#gid=406612277

**Comment by garimadosar5** [comment]
QA Notes - 
- Question "Marital status". if other is selected Specify other text is not coming.
![Screen Shot 2020-05-14 at 4.56.33 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/4c93cb28-4885-4485-96f2-85f8b14020ff)
-

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 " Fixed
