### ISSUE TITLE
[JSSCP] [UAT Feedback] ANC Clinic Visit 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#68]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=1132231519

**Comment by garimadosar5** [comment]
QA Notes - 
- Question "FHS number" is missing.
![Screen Shot 2020-05-13 at 6.34.13 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/a9fda483-8f20-419f-a0a6-6fe1c4625276)

**Comment by nupoorkhandelwal** [comment]
@garima For "FHS" option "Actual data entry" was not there .Removed it. FHS number show if one selects "Audible"

And for first ANC visit, one needs to select date of ANC in the enrolment form.It schedules for the date selected. Please check

**Comment by garimadosar5** [comment]
QA Notes - 
- "Glucose Test" is not showing. in 7th month ANC.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5   Fixed the "Glucose Test" issue.

For which case is this issue >> "First ANC Clinic visit is scheduling just after Pregnancy enrolment"
