### ISSUE TITLE
[JSSCP] [UAT Feedback] Pregnancy Enrolment

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#69]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=534785871

**Comment by garimadosar5** [comment]
QA Notes - 
- Question "High-risk condition in last pregnancy" option 13 is missing.
![Screen Shot 2020-05-13 at 6.25.22 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/fca4a34e-9be3-4e07-a8e8-b8be406ec0eb)
