### ISSUE TITLE
[JSSCP] [UAT Feedback] ANC Home Visit

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#70]
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=2081054628

**Comment by garimadosar5** [comment]
QA Notes - 
- Question "New complaint", in Home ANC also the new option "Vomiting" should be added.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 I have checked both the points and they are working.![screenshot-2020-05-13_19.49.59.967.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/4a6cce50-2347-48d7-8bac-5d90143f4dd5)![screenshot-2020-05-13_19.50.31.733.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/597bf9cb-0de0-409a-857a-f947095e91e2)

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 
The first point is showing but second is still not showing.
