### ISSUE TITLE
[JSSCP] [UAT Feedback] Mother PNC

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#72]
For related changes-- 
https://docs.google.com/spreadsheets/d/1FFMRLGWfnRlZ6jxIft7cBHOjdMdhcKLbkomaUdrE1a8/edit#gid=1610300197

**Comment by garimadosar5** [comment]
QA Notes - 
- In mother PNC detailed counselling points are given in the sheet. but we are showing only the titles of these counselling points.
![Screen Shot 2020-05-14 at 4.53.43 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/c55f6afc-8282-4dce-b067-a95c054d69de)

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 We have not yet uploaded translations for the implementation.Will add them once changes are confirmed on UAT.
