### ISSUE TITLE
[JSSCP] [UAT Feedback] Child Module 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#76]
Mark abnormal conditions

Fix visit scheduling issue.

**Comment by garimadosar5** [comment]
QA Notes - 
On Visit Schedule - 
Case - Baby Shah
- for child PNC 3 is scheduled, if I edit birth form it overwrites the PNC 3 (19th May 20) to PNC 4 (27 May 20). Now again I edit the Birth form, it overwrites the PNC 4(27 May 20) with PNC 3 (19 May 20).
-
