### ISSUE TITLE
[JSSCP] User training feedback changes

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#77]
https://docs.google.com/spreadsheets/d/1c_llCuCl-l_BQ1a92riBbBVZ0OGbzi20Xm350DP4Zqk/edit#gid=980503221

1. Update Cancel Reason Option -- For mother program ANC visits, Add new option "Delivery/Abortion" and dont show the next ANC visit details screen.
2. Add an autogenerated enrolmentID for Mother program in the Enrolment form.

Delivery Form
3. Add date and time of baby out as per requirment document

Child birth 
4.Logic for "Newborn observations after 5 mins " for concept "Diagnosis of baby immediately after birth">> "still birth " Also dont schedule PNC in case of still birth 

Child PNC
5. Update High risk conditions

**Comment by garimadosar5** [comment]
QA Notes - 
- Point - 1. Cancel option is added only for ANC clinic, not for ANC home visit.
- Point - 2. Enrollment id format is "ANC7000", not sure if this is the format required. Check
- Point - 4. In the case of stillbirth "Newborn observation after 30 seconds" is required?
-
