### ISSUE TITLE
[JSSCP] Move MCH module form JSSCP UAT to JSSCP production org

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#78]
1. Move Phulwari registration fields to Phulwari enrolment.
2. Move new changes for MCH, individual and household registration 
3. Upload locations and users for MCH
4. Upload Individual registration, household registration and household members data upload
5. Upload translations for the same.
6. Add user auto generated id assignment as per the requirement.

** This will be done once all the users have done sync**

**Comment by nupoorkhandelwal** [comment]
1. Shared Locations already exists on JSSCP prod. Only location >> Shivtarai >> Surajpur
2.

**Comment by garimadosar5** [comment]
QA Notes - 
- Individual data import - 
                  - All individuals are not imported. for eg: id 1 is not there in the system.
-
