### ISSUE TITLE
[JSSCP][Report] Intranatal Services.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#80]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=96095858

**QA Checklist -** 
- [x] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [x] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- There are total 47 deliveries reported. In report it is showing 39 only.

**Comment by vindeolal** [comment]
@garimadosar5 All the changes are done.
