### ISSUE TITLE
[JSSCP][Report] Birth and Death Rates.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#82]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=96095858

**Comment by hithacker** [comment]
@garimadosar5 I changed the logic to not include stillbirths for mortality in the initial query itself instead of substracting it later so it's working fine now. Let me know over chat if you have any questions.
