### ISSUE TITLE
[JSSCP][Report] Post Natal Children

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#86]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=96095858

**QA Checklist -** 
- [x] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [x] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- What is the logic for indicator "Total children enrolled"?
- Percentage Column - put 0.00% or 0% not .00%.
- Age filter is weeks or months.
- Line list - Diagnosis of sepsis column is missing.
- Put S.No on line list.

**Comment by sachsk** [comment]
diagnosis of sepsis question is not present in form(removed)
