### ISSUE TITLE
[JSSCP][Report] Children Post Natal Services

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#89]
https://docs.google.com/spreadsheets/d/1N6pT88Ez2feCK1qSWiRLBko4aKE0wCc7AWwVNRwTD3M/edit#gid=96095858

**QA Checklist -** 
- [x] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- Numbers are not getting updated in the report after change in-app. except the indicator "Children breastfed 8 times a day".
Case - Geeta Yadav (name is in Hindi in app).

**Comment by sachsk** [comment]
No. is updating (please make changes in the latest encounter)
gender filter Is working fine for both report
age is renamed to age in months
