### ISSUE TITLE
[JSSCP] Create Visits for Next growth monitoring and Albendazole.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#9]
Create albendazole -feb for each child in the system.
And create the Growth monitoring visit for each child.

Ref Doc - 
https://docs.google.com/spreadsheets/d/1SYjRmm9IkaWDzEnCq_znmxanQvQlhUtr/edit#gid=1357041330

**Comment by garimadosar5** [comment]
QA Notes - 
- Growth monitoring schedule for January 2020 month.

**Comment by vindeolal** [comment]
Deleted wrongly scheduled visits and created for JAN month. Users need to delete data (uninstall App) so that old visits don't show up.
